config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  #   post '/questions', to: 'questions#create'
  #   patch 'questions/:id', to: "questions#update"
  #   delete '/questions/:id', to: 'questions#destroy'

  root to: 'questions#index'

  resources :questions

  resource :session, only: %i[new create destroy]

  resources :users, only: %i[new create edit update]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  validates :body, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  before_save :downcase_nickname

  validates :email, :nickname, :name, :password_digest, presence: true
  validates :email, uniqueness: true

  def downcase_nickname
    nickname.downcase!
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  #   skip_before_action :verify_authenticity_toke

  before_action :set_question, only: %i[update show destroy edit]

  def create
    question = Question.create(init_params)

    flash[:notice] = 'Your question has been created.'

    redirect_to question_path(question), notice: 'Your question has been created.'
  end

  def update
    @question.update(init_params)
    redirect_to question_path(@question), notice: 'Your question has been updated.'
  end

  def destroy
    @question.destroy

    redirect_to questions_path, notice: 'Your question has been deleted.'
  end

  def show; end

  def index
    @questions = Question.all
    @question = Question.new
  end

  def new
    @question = Question.new
  end

  def edit; end

  private

  def init_params
    params.require(:question).permit(:body, :user_id)
  end

  def set_question
    @question = Question.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user_params = params.require(:session)

    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id

      redirect_to root_path, notice: 'Successfully logged in!'
    else
      flash.now[:alert] = 'Something wrong with email and password.'

      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'Successfully logged out!'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: 'Account created!'
    else
      flash.now[:alert] = 'Incorrect input!'

      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to root_path, notice: 'Successfully updated!'
    else
      flash.now[:alert] = 'Incorrect input!'

      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:name, :nickname, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def inclination(count, one, few, many)
    return many if (count % 100).between?(11, 14)

    case count % 10
    when 1 then one
    when 2..4 then few
    else
      many
    end
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
   <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <%= favicon_link_tag 'favicon-16x16.png' %>

    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Arvo:wght@400;700">

    <link rel="stylesheet"
     href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
       crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" 
    integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
     crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>

  <div class="wrapper-main ">
  <nav class="navbar-main navbar navbar-expand-md row 
    d-flex align-items-center" >
  <div class="container-fluid d-flex align-items-center">
    <div class="container-nav col-auto text-wrap">
      <%= link_to "ASKME", root_path, class: "navbar-brand", style: "margin-left: 5px"%>
    </div>
    <div class="col-md-6 col-lg-6 col-sm-6"></div>
    <% if current_user.present? %>
    <div class="container-nav col-auto ">
       

        <p class="username">
          <%= link_to "@#{current_user.nickname}", edit_user_path(current_user)%>
          </p>
      </div>
    <div class="container-nav col-auto ">
      <%= button_to 'Logout', session_path, method: :delete, class: "btn btn-danger username"%>
    </div>
    <% else %>
    <div class="container-nav col-auto text-wrap">
      <%= link_to "Register", new_user_path, class: "nav-item nav-link"%>
    </div>
      <div class="container-nav col-auto text-wrap">
      <%= link_to "Login", new_session_path, class: "nav-item nav-link"%>
    </div>
      
    <% end %>
    </div>
</nav>


    <% if flash[:notice].present? %>
      <p class="mb mt message message-notice"><%= flash[:notice] %> </p>
    <% end %>

    <% if flash[:alert].present? %>
      <p class="mb mt message message-alert"><%= flash[:alert] %> </p>
    <% end %>

    <%= yield %>


  </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: question do |form| %>
<div class="container-question-create mt-md">
  <p><%= form.label :body, "Text" %></p>
  <p><%= form.text_area :body, rows: 5, class: "form-textarea" %></p>
  <p><%= form.label :body, "More text" %></p>
  <p><%= form.text_field :user_id, class: "form-textarea"%></p>
  </div>
  <div class="container-question-create mt-md">
  <p><%= form.submit "Save", class: "btn-create"%></p>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div class="mb-sm text-md italic">
  <%= question.body%>
</div>
<div class="text-sm">
  <div class=" question_footer line-footer">
    <%= l(question.created_at, format: :short, class: "text-right text-dark-grey") %>
    <div class="container-icons">
    <%= button_to fa_icon('pencil'), edit_question_path(question), method: :get, title: "Redact question", class: "button_del" %>
    <%= button_to fa_icon("trash-o"), question_path(question), method: :delete, title: "Delete question", class: "button_del" %>
  </div>
  </div>
</div>

app/views/questions/edit.html.erb
<div class="container-question-create align-center ">

  <h2 class="title-question"> Edit question "<%= @question.body %>"</h2>
</div>

<%= render 'form', question: @question %>

app/views/questions/index.html.erb
 <div class="parent-container-btn">
  <div class="container-btn mb-md ">
    <%= link_to "Create new question", new_question_path, class: "text-add-question" %>
  </div>
</div>

<% @questions.each do |question| %>
  <div class="mt-md container-question">
    <%= render question %>
  </div>
<% end %>

app/views/questions/new.html.erb
<div class="container-question-create align-center ">

  <h2 class="title-question">New question</h2>
</div>
  <%= render 'form',  question: @question%>

app/views/questions/show.html.erb
<div class="container-question-info">
  <h2 class="title-question">Question with user_id: <h class="italic"><%= @question.user_id %></h></h2> 
<%= render @question%>
    <%= button_to fa_icon('home'), questions_path, method: :get, title: "Go home page", class: "button_home" %>

</div>

app/views/users/edit.html.erb
<div class="container-user ">
  <h2 class="title">Edit users info</h2>
  <div class="mt" >
    <%= form_with model: @user, url: user_path(@user), method: :patch, data: {turbo: false} do |form| %>
      <div class="container-field mb-sm">
      <p><%= form.label :name, "Your name" %></p>
      <p><%= form.text_field :name , class: "form-textfield" %></p>
      </div>

      <div class="container-field mb-sm ">
      <p class="mt"><%= form.label :nickname, "Your @nickname" %></p>
      <p><%= form.text_field :nickname , class: "form-textfield" %></p>
      </div>


  <div class="container-field mb-sm">
      <p class="mt error-text"><%= form.label :password, "Password" %></p>
      <p><%= form.password_field :password , class: "form-textfield"%></p>
      </div>
      <div class="error-text container-field mb-sm">
      <p class="mt"><%= form.label :password_confirmation, "Password" %></p>
      <p><%= form.password_field :password_confirmation , class: "form-textfield"%></p>
</div>
      <p class="mt-lg"><%= form.submit "Edit", class: "button-confirm" %></p>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
  <div class="container-user" >
      <h2 class="title mb-md">Join & Ask ^~^</h2>
      <% if @user.errors.any? %>
  <div class="mt">
    <% @user.errors.full_messages.each do |message| %>
    <div class="align-left mb-sm">
      <div class="container-error">
        <p class="mb error-text"><%= message %></p>
      </div>
    </div>
    <% end %>
  </div>
<% end %>
    <%= form_with model: @user, data: {turbo: false} do |form| %>
      <div class="container-field mb-sm text-field">
      <p><%= form.label :name, "Your name" %></p>
      <p><%= form.text_field :name , class: "form-textfield" %></p>
      </div>

      <div class="container-field mb-sm">
      <p class="mt"><%= form.label :nickname, "Your @nickname" %></p>
      <p><%= form.text_field :nickname , class: "form-textfield" %></p>
      </div>

      <div class="container-field mb-sm">
      <p class="mt"><%= form.label :email, "Email" %></p>
      <p><%= form.text_field :email ,
       class: "form-textfield", placeholder: "example@askme.com" %></p>
      </div>

      <div class="container-field mb-sm">
      <p class="mt"><%= form.label :password, "Password" %></p>
      <p><%= form.password_field :password , class: "form-textfield"%></p>
      </div>

      <div class="container-field mb-sm">
       <p class="mt"><%= form.label :password_confirmation, "Password" %></p>
      <p><%= form.password_field :password_confirmation , class: "form-textfield"%></p>
      </div>
      <p class="mt-md"><%= form.submit "Register", class: "button-confirm" %></p>

    <% end %>
  </div>